### ISSUE TITLE
    faild: assert visual_features.shape[0] == self.vf_size AssertionError

### ISSUE THREAD

**Issue by SeekPoint** [mjhucla/TF-mRNN#6]
rzai@rzai00:~/prj/TF-mRNN$ CUDA_VISIBLE_DEVICES=1 python ./exp/ms_coco_caption/mrnn_trainer_mscoco.py
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.37GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
[21 Dec 10:52:00 - tf_data_provider.py:line  105] Loading data
[21 Dec 10:52:44 - tf_data_provider.py:line  136] Load 5000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:53:20 - tf_data_provider.py:line  136] Load 10000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:53:56 - tf_data_provider.py:line  136] Load 15000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:54:33 - tf_data_provider.py:line  136] Load 20000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:55:04 - tf_data_provider.py:line  136] Load 25000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:55:41 - tf_data_provider.py:line  136] Load 30000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:56:18 - tf_data_provider.py:line  136] Load 35000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:56:57 - tf_data_provider.py:line  136] Load 40000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:57:33 - tf_data_provider.py:line  136] Load 45000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:58:09 - tf_data_provider.py:line  136] Load 50000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:58:46 - tf_data_provider.py:line  136] Load 55000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 10:59:23 - tf_data_provider.py:line  136] Load 60000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:00:02 - tf_data_provider.py:line  136] Load 65000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:00:39 - tf_data_provider.py:line  136] Load 70000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:01:19 - tf_data_provider.py:line  136] Load 75000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:01:56 - tf_data_provider.py:line  136] Load 80000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:02:38 - tf_data_provider.py:line  136] Load 85000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:03:18 - tf_data_provider.py:line  136] Load 90000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:03:53 - tf_data_provider.py:line  136] Load 95000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:04:29 - tf_data_provider.py:line  136] Load 100000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:05:06 - tf_data_provider.py:line  136] Load 105000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:05:43 - tf_data_provider.py:line  136] Load 110000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:06:21 - tf_data_provider.py:line  136] Load 115000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:06:59 - tf_data_provider.py:line  136] Load 120000/122286 annotation from file ./datasets/ms_coco/mscoco_anno_files/anno_list_mscoco_trainModelVal_m_RNN.npy
[21 Dec 11:07:13 - tf_data_provider.py:line  140] Load 122285 images, 611755 sentences from 1 files, 1 image failed
Traceback (most recent call last):
  File "./exp/ms_coco_caption/mrnn_trainer_mscoco.py", line 172, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "./exp/ms_coco_caption/mrnn_trainer_mscoco.py", line 163, in main
    data_provider, verbose=True)
  File "./exp/ms_coco_caption/mrnn_trainer_mscoco.py", line 75, in run_epoch
    data_provider.generate_batches(config.batch_size, config.buckets)):
  File "./py_lib/tf_data_provider.py", line 97, in generate_batches
    feed_res = batches[ind_b].feed_and_vomit(visual_features, sentence)
  File "./py_lib/tf_data_provider.py", line 52, in feed_and_vomit
    assert visual_features.shape[0] == self.vf_size
AssertionError
rzai@rzai00:~/prj/TF-mRNN$

**Comment by alexandrazxf** [comment]
你解决了吗？我遇到了同样的问题吖~ @loveJasmine

**Comment by hjl150505** [comment]
我这里没有mrnn_GRU_mscoco.py，只有mrnn_GRU_mscoco_VGG.py，我把mrnn_GRU_mscoco.py名字改成了mrnn_GRU_mscoco_VGG.py，但是加载完数据之后就出现楼主列出的错误，有谁解决了吗？
