### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './model_conf/mrnn_GRU_mscoco.py'

### ISSUE THREAD

**Issue by hjl150505** [mjhucla/TF-mRNN#7]
TF-mRNN-master$ cp ./model_conf/mrnn_GRU_mscoco_vgg.py ./model_conf/mrnn_GRU_mscoco.py
[20 Mar 17:47:33 - tf_data_provider.py:line  105] Loading data
.....
[20 Mar 17:45:27 - tf_data_provider.py:line  140] Load 122285 images, 611755 sentences from 1 files, 1 image failed
Traceback (most recent call last):
  File "./exp/ms_coco_caption/mrnn_trainer_mscoco.py", line 172, in <module>
    tf.app.run()
  File "/home/bst/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "./exp/ms_coco_caption/mrnn_trainer_mscoco.py", line 163, in main
    data_provider, verbose=True)
  File "./exp/ms_coco_caption/mrnn_trainer_mscoco.py", line 75, in run_epoch
    data_provider.generate_batches(config.batch_size, config.buckets)):
  File "./py_lib/tf_data_provider.py", line 97, in generate_batches
    feed_res = batches[ind_b].feed_and_vomit(visual_features, sentence)
  File "./py_lib/tf_data_provider.py", line 52, in feed_and_vomit
    assert visual_features.shape[0] == self.vf_size
AssertionError

**Comment by JingyaLiu** [comment]
@hjl150505 did you solve the problem? I encounter with the same error.
